### ISSUE TITLE
DDR4 training ?

### ISSUE THREAD

**Issue by natinusala** [rajkosto/memloader#1]
In [this blog post](https://fail0verflow.com/blog/2018/shofel2/), the fail0verflow team states that to have full speed RAM we must extract a blob from a Pixel C factory image. This blob is then used by coreboot to train the DDR4 RAM of the console.

How does memloader handle this when booting directly a u-boot binary ?

**Comment by rajkosto** [comment]
It doesn't if you launch u-boot directly.
To install the secure monitor and run memory training, you would boot fallback/ramstage from coreboot.rom
