### ISSUE TITLE
Help with step 2. How do I use memloader over USB and without a micro SD card?

### ISSUE THREAD

**Issue by raindew120** [rajkosto/memloader#10]
I have a Switch which micro SD card reader has stopped working due to a short circuit in the connector. I was told by the repair company that an attempted repair could cause the entire main board to stop working, and if it does, all of my saves will be gone. So I’ve been trying to find a way to mount my Switch’s NAND to my computer without a micro SD card via memloader, and then copying out all of my save data.

I noticed that it says in step 2:

“Either put the appropriate ini+binary files onto your microsd card before inserting it into your Switch, **or pass the --dataini parameter to TegraRcmSmash.exe to load them via USB.**”

Is there anyone who could provide me with specific step-by-step instructions on how to do that? Which specific ini+binary files in the .zip folder do i pass, and how do I pass the --dataini parameter? Sorry if this is a dumb question.

**Comment by leo60228** [comment]
For what it's worth, replacing the microSD card reader is one of the easiest repairs to do on the Switch. You just remove a few screws and snap it into place. https://www.ifixit.com/Guide/Nintendo+Switch+Micro+SD+Card+Reader+Replacement/113031

**Comment by raindew120** [comment]
No. It’s not the card reader that’s broken. We tried replacing the reader already to no avail. We later sent it to a repair company, and found out that it was due to a short circuit in the motherboard. The connector, which is part of the motherboard, is broken, and needs to be repaired. If it fails, we have to replace the entire motherboard.

**Comment by raindew120** [comment]
> For what it's worth, replacing the microSD card reader is one of the easiest repairs to do on the Switch. You just remove a few screws and snap it into place. https://www.ifixit.com/Guide/Nintendo+Switch+Micro+SD+Card+Reader+Replacement/113031

No. It’s not the card reader that’s broken. We tried replacing the reader already to no avail. We later sent it to a repair company, and found out that it was due to a short circuit in the motherboard. The connector, which is part of the motherboard, is broken, and needs to be repaired. If it fails, we have to replace the entire motherboard.

**Comment by raindew120** [comment]
Update: My Switch was successfully repaired in the end, so I’ll be closing this now.
